### ISSUE TITLE
Regarding Class labels

### ISSUE THREAD

**Issue by imnaren142** [DhavalThkkar/Transfer-Learning#1]
In this model how to set class labels for each category?

**Comment by naren142** [comment]
Validation accuracy is not changing when I trained with my own data.

**Comment by DhavalThkkar** [comment]
The class labels are generated automatically when you create folders for different classes.
For example: If you have 3 categories(classes) dog, cat, monkey. You need to create folders for each of the class labels and create train and test folders inside each category, everything else is taken care of by the script
